name: "JFrog CLI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
#on: release

permissions:
  # This is required for requesting the OIDC token
#  id-token: write
  # This is required for actions/checkout
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          # JF_URL: ${{ vars.JF_URL }}
          JF_URL: ${{ vars.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          RT_URL_L: ${{ vars.JF_URL }}

      - name: Run JFrog CLI
        run: |
          jf -v
          echo artifactory url: ${{ vars.JF_URL }}
          echo "Ping the server"
          jf rt ping
          echo "jf show config"
          jf config show > f1
          cat f1

  evidence-collection:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
      - name: Run jq
        uses: sergeysova/jq-action@v2
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - name: Release Info Evidence
        run: |
          JSON=$(jq -n \
            --arg commit ${{ github.event.commits[0].id }} \
            --arg review "Marie Lupen" \
            --arg reviewers "Maries Lupens" \
            '$ARGS.named'
          )
          echo "$JSON"
          
          echo "github.event: ${{ toJson(github.event) }}"